In [1]:
import pandas as pd
import numpy as np

In [7]:
p_list = [10,20,30,40,23]
print(p_list)

[10, 20, 30, 40, 23]


In [3]:
type(p_list)

list

In [5]:
a_np = np.array(p_list)

In [8]:
print(a_np)

[10 20 30 40 23]


In [9]:
arr = []  
for i in p_list:       #using for loop
    arr.append(i * 10)
print(arr)

[100, 200, 300, 400, 230]


In [13]:
list(map(lambda i: i*10, p_list))  # using map and lambda

[100, 200, 300, 400, 230]

In [14]:
print([i*10 for i in p_list])  # using list comprehension

[100, 200, 300, 400, 230]


In [15]:
a_np * 10

array([100, 200, 300, 400, 230])

In [20]:
new_arr = np.array([1,2,3, 4.5])
print(new_arr)

[1.  2.  3.  4.5]


In [21]:
new_arr.dtype

dtype('float64')